name: ${pluginName}
version: ${pluginVersion}
description: ${pluginDescription}
author: ${pluginAuthor}
website: ${pluginWebsite}
main: host.bloom.ab.bukkit.BukkitPlugin
api-version: 1.13
commands:
  bloomab: {}
