# This is the configuration file for BloomAB
# For any questions, please contact us at: discord.gg/bloom

limits:
  trigger-duration: 120
  max-joins-per-second: 120

api:
  endpoint: disabled
  secret: disabled

options:
  catch-raw-connections: false
  block-new-joins: NEW_PLAYERS_ONLY
  check-for-updates: true
